version: '2'
services:
    catalog-app:
        image: catalog
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://catalog-postgresql:5432/Catalog
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9004:9004
    catalog-postgresql:
        extends:
            file: postgresql.yml
            service: catalog-postgresql
